@Library("jenlib@ebrains-4.0") _

Map<String, Object> pipelineOptions = [
		projects: ["nhtl-extoll"],
		setupOptions: "--release-branch=ebrains-4.0",
		container: [app: "dls-core"],
		moduleOptions: [modules: ["extoll"]],
		notificationChannel: "#dls-software",
		testSlurmResource: [partition: "extoll", wafer: 61, "cpus-per-task": "4", "mem": "8G"]
]

wafDefaultPipeline(pipelineOptions)
