@Library("jenlib") _

Map<String, Object> pipelineOptions = [
		projects: ["nhtl-extoll"],
		container: [app: "dls-core"],
		notificationChannel: "#dls-software"
]

wafDefaultPipeline(pipelineOptions)
